requires 'Class::Accessor::Fast';
requires 'Encode::Locale';
requires 'Encode::UTF8Mac';
requires 'Encode';
requires 'HTML::Entities';
requires 'HTML::TreeBuilder';
requires 'JSON::PP';
requires 'Text::Markdown::Discount';
requires 'Web::Query';
requires 'YAML';
# requires 'https://github.com/hatyuki/p5-Text-Markdown-GFM-Lite/tarball/master';
